### ISSUE TITLE
In Keras implementation training data is used for testing

### ISSUE THREAD

**Issue by adezfouli** [omitakahiro/NeuralNetworkPointProcess#1]
In the Keras implementation, `keras_implementation.ipynb`, the Training data is used for Testing (sections Test1, Test2).

**Comment by omitakahiro** [comment]
Thank you for letting me know it. I fixed it.

**Comment by adezfouli** [comment]
OK thanks. Shouldn't `np.mean(dT_test)` be based on trining data though?

**Comment by omitakahiro** [comment]
Thanks. I changed `np.mean(dT_test)` -> `np.mean(dT_train)`.
