### ISSUE TITLE
Target is provided as input?

### ISSUE THREAD

**Issue by ruben20101** [omitakahiro/NeuralNetworkPointProcess#2]
Hi,

I love the idea of this but I'm not sure I understand the data given to the model. I notice d_test_target/input_chfn is submitted as the second input to the model alongside event history. This is given as the next interval following the event history. Surely this should be the output of the model and the target should be used for evaluation as it would not be known in a real world environment?

**Comment by omitakahiro** [comment]
Thanks, 

Our model is a probabilistic model, which essentially predicts the probability density function `p(tau|H)` of the next interval `tau` conditioned on the event history `H`. When training, the observed value of the next interval is inputted to the network to evaluate the log-likelihood of the model.

When one wants to predict the next interval given the history with our model, we input several values of `tau`, say `tau_1, tau_2, tau_3, ...`, to the network and  obtain `p(tau_1|H), p(tau_2|H), p(tau_3|H), ...` first, and then numerically calculate the mean or the median of the predictive distribution. This is described in the last paragraph of the method section in our original paper. Or please see TEST2 section in our notebook (https://github.com/omitakahiro/NeuralNetworkPointProcess/blob/master/keras_implementation.ipynb).

I hope this makes sense.
