### ISSUE TITLE
Non-negative constraints on the parameters of Cumulative Hazard Function Network

### ISSUE THREAD

**Issue by PDP-11** [omitakahiro/NeuralNetworkPointProcess#3]
Hi,

I read your paper and found a training trick on *page* 4, *footnote* 3:
> In order to enforce the weights to be positive, if a weight is updated to be a negative value during training,
we replace it with its absolute value.

However in your `Keras`  implementation,  you just create a layer with
```python
kernel_constraint=keras.constraints.NonNeg()
```
I cannot see why they are equivalent and would such constraints have any side (negative) effects?

Many Thanks!

**Comment by omitakahiro** [comment]
Thanks,
I might slightly misunderstand the detail of the implementation of `keras.constraints.NonNeg()`. In our paper, we used `keras.constraints.NonNeg()` to constrain particular network weights to be non-negative.
