### ISSUE TITLE
Unclear how to run - errors given with newest version of tensorflow

### ISSUE THREAD

**Issue by mattclifford1** [omitakahiro/NeuralNetworkPointProcess#4]
default version of tensorflow (2.4) causes error when running - will submit a pull request to amend this

**Comment by mattclifford1** [comment]
https://github.com/omitakahiro/NeuralNetworkPointProcess/pull/5
should clarify this

**Comment by omitakahiro** [comment]
Thanks. I merged the pull request to a new branch `python_setup`, and will change the top page to let the users to know this issue.
